# Generated by Django 4.2.27 on 2025-12-15 02:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('transaction', 'Transaction'), ('term_deposit', 'Term Deposit'), ('offset', 'Offset'), ('other', 'Other')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='CryptoHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('average_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=15)),
                ('wallet_address', models.CharField(blank=True, max_length=200)),
                ('exchange', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ETFHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('units', models.DecimalField(decimal_places=6, max_digits=15)),
                ('average_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('exchange', models.CharField(default='ASX', max_length=20)),
                ('units', models.DecimalField(decimal_places=6, max_digits=15)),
                ('average_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='SuperannuationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('member_number', models.CharField(blank=True, max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('personal_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('investment_option', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('drp', 'Dividend Reinvestment')], max_length=20)),
                ('date', models.DateField()),
                ('units', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('brokerage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.stockholding')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETFTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('distribution', 'Distribution'), ('drp', 'Dividend Reinvestment')], max_length=20)),
                ('date', models.DateField()),
                ('units', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('brokerage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.etfholding')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('staking_reward', 'Staking Reward'), ('airdrop', 'Airdrop')], max_length=20)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fee', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('exchange', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.cryptoholding')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
