# Generated by Django 4.2.27 on 2025-12-15 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_bankaccount_user_cryptoholding_user_etfholding_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('AUD', 'Australian Dollar (AUD)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('NZD', 'New Zealand Dollar (NZD)'), ('CAD', 'Canadian Dollar (CAD)'), ('JPY', 'Japanese Yen (JPY)'), ('SGD', 'Singapore Dollar (SGD)'), ('HKD', 'Hong Kong Dollar (HKD)'), ('CHF', 'Swiss Franc (CHF)')], default='AUD', max_length=3)),
                ('timezone', models.CharField(choices=[('Australia/Sydney', 'Sydney (AEST/AEDT)'), ('Australia/Melbourne', 'Melbourne (AEST/AEDT)'), ('Australia/Brisbane', 'Brisbane (AEST)'), ('Australia/Perth', 'Perth (AWST)'), ('Australia/Adelaide', 'Adelaide (ACST/ACDT)'), ('Australia/Darwin', 'Darwin (ACST)'), ('Australia/Hobart', 'Hobart (AEST/AEDT)'), ('Pacific/Auckland', 'Auckland (NZST/NZDT)'), ('Asia/Singapore', 'Singapore (SGT)'), ('Asia/Hong_Kong', 'Hong Kong (HKT)'), ('Asia/Tokyo', 'Tokyo (JST)'), ('Europe/London', 'London (GMT/BST)'), ('Europe/Paris', 'Paris (CET/CEST)'), ('America/New_York', 'New York (EST/EDT)'), ('America/Los_Angeles', 'Los Angeles (PST/PDT)'), ('UTC', 'UTC')], default='Australia/Sydney', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User preferences',
            },
        ),
    ]
