# Generated by Django 4.2.27 on 2025-12-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='country',
            field=models.CharField(blank=True, default='Australia', max_length=100),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
