# Generated by Django 4.2.27 on 2025-12-15 03:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userpreferences_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperannuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employer contributions this month', max_digits=15)),
                ('personal_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Personal contributions this month', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.superannuationaccount')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
