# Generated by Django 4.2.27 on 2025-12-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_superannuationsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoholding',
            name='coingecko_id',
            field=models.CharField(blank=True, help_text="CoinGecko ID for price fetching (e.g., 'bitcoin', 'ethereum')", max_length=100),
        ),
    ]
