# Generated by Django 5.2.9 on 2025-12-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cryptoholding_coingecko_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfholding',
            name='exchange',
            field=models.CharField(choices=[('ASX', 'ASX (Australian)'), ('NYSE', 'NYSE (US)'), ('NASDAQ', 'NASDAQ (US)'), ('LSE', 'LSE (UK)'), ('OTHER', 'Other')], default='ASX', max_length=10),
        ),
    ]
