# Generated by Django 5.2.9 on 2025-12-29 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_etfholding_exchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('asset_type', models.CharField(choices=[('bank', 'Bank Account'), ('super', 'Superannuation'), ('etf', 'ETF Holding'), ('stock', 'Stock Holding'), ('crypto', 'Cryptocurrency')], max_length=20)),
                ('asset_name', models.CharField(help_text="Name of the asset (e.g., 'ANZ Savings', 'VGS')", max_length=200)),
                ('asset_identifier', models.CharField(blank=True, help_text='Symbol or account number for reference', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, help_text='Asset value at snapshot date', max_digits=15)),
                ('quantity', models.DecimalField(blank=True, decimal_places=10, help_text='Quantity/units for investments (optional)', max_digits=20, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=4, help_text='Price per unit for investments (optional)', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'asset_type', 'asset_name'],
                'indexes': [models.Index(fields=['user', 'date'], name='api_assetsn_user_id_d043de_idx'), models.Index(fields=['user', 'asset_type', 'date'], name='api_assetsn_user_id_f76b77_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networth_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
