# Generated by Django 5.2.9 on 2025-12-30 01:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_assetsnapshot_networthsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsnapshot',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Price per unit for investments (optional)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='assetsnapshot',
            name='value',
            field=models.DecimalField(decimal_places=10, help_text='Asset value at snapshot date', max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptoholding',
            name='average_price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptoholding',
            name='current_price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
